author: Zack
description: A minigame that allows players to have their own skyblock world

main: com.zack.minigame_Skyblock.Main
name: minigame_Skyblock
version: 1.1.0
api-version: 1.18
commands:
  skyblock:
    aliases: [sb]
    description: Your own skyblock world!