author: Zack
description: A stopwatch and coundown plugin

main: com.zack.serveressentials_Clock.Main
name: serveressentials_Clock
version: 1.0.0
api-version: 1.17
commands:
  stopwatch:
    description: Controls your individual stopwatch
  countdown:
    description: Controls your individual countdown