author: Zack
description: A world generator plugin

main: com.zack.serveressentials_WorldGenerator.Main
name: serveressentials_WorldGenerator
version: 1.3.2
api-version: 1.17
commands:
  generateworld:
    description: Allows OPs to create new worlds for various purposes
  unloadworld:
    description: Allows OPs to unload created worlds
  worldname:
    description: Debug command enabling you to get the name of the world you are in
  tpworld:
    description: Allows OPs to teleport players to custom worlds