author: Zack
description: A world editor plugin

main: com.zack.serveressentials_WorldEdit.Main
name: serveressentials_WorldEdit
version: 1.2.0
api-version: 1.18
commands:
  superblock:
    description: Gives OPs a block that creates a tower up to a set height